image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Build & publish to production
          deployment: production
          caches:
            - node
          script:
            - npm install
            - npm install -g gulp-cli
            - gulp build
            - gulp publish --awsk $AWS_ACCESS_KEY_ID --awss $AWS_SECRET_ACCESS_KEY --production
      # - step:   # Uncomment to add Cloudfront Invalidation step
      #     name: Invalidate Cloudfront objects
      #     script:
      #       - pipe: atlassian/aws-cloudfront-invalidate:0.1.3
      #         variables:
      #           AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      #           AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      #           AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      #           DISTRIBUTION_ID: '$AWS_CF_DISTRIBUTION'
      #           PATHS: '$AWS_CF_PATHS'

    development:
      - step:
          name: Build & publish to staging
          deployment: staging
          caches:
            - node
          script:
            - npm install
            - npm install -g gulp-cli
            - gulp build
            - gulp publish --awsk $AWS_ACCESS_KEY_ID --awss $AWS_SECRET_ACCESS_KEY
